
version: "3.2"
services:

  data_ingestion:
    build:
      context: src/data_ingestion
      dockerfile: Dockerfile
    environment:
      - db_path=${db_path}
      - customer_db=${customer_db}
      - config_path=${config_path}
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - /home/fresh/Documents/Workflow/Customer-retention/databases:/app/databases
      - /home/fresh/Documents/Workflow/Customer-retention/configs:/app/configs
      - /home/fresh/Documents/Workflow/Customer-retention/data:/app/data

  model_training:
    build:
      context: src/model_training
      dockerfile: Dockerfile
    environment:
      - config_path=${config_path}
    ports:
      - "8001:8001"
    expose:
      - 8001
    volumes:
      - /home/fresh/Documents/Workflow/Customer-retention/databases:/app/databases
      - /home/fresh/Documents/Workflow/Customer-retention/configs:/app/configs
      - /home/fresh/Documents/Workflow/Customer-retention/data:/app/data
      - /home/fresh/Documents/Workflow/Customer-retention/mlruns:/app/mlruns

  model_deployment:
    build:
      context: src/model_deployment
      dockerfile: Dockerfile
    environment:
      - config_path=${config_path}
      - db_path=${db_path}
      - customer_db=${customer_db}
      - MLFLOW_TRACKING_URI=sqlite:///databases/mlflow.db
    ports:
      - "8002:8002"
    expose:
      - 8002
    volumes:
      - /home/fresh/Documents/Workflow/Customer-retention/databases:/app/databases
      - /home/fresh/Documents/Workflow/Customer-retention/configs:/app/configs
      - /home/fresh/Documents/Workflow/Customer-retention/data:/app/data
      - /home/fresh/Documents/Workflow/Customer-retention/mlruns:/app/mlruns
