version: "3.2"

networks:
  customer_retention_network:
    driver: bridge

services:
  ml_stack:
    build:
      context: src/core
      dockerfile: Dockerfile
    environment:
      - config_path=${config_path}
      - MLFLOW_TRACKING_URI=${mlflow_tracking_uri}
    ports:
      - "8002:8002"
    expose:
      - 8002
    volumes:
      - ./databases:/app/databases
      - ./configs:/app/configs
      - ./data:/app/data
      - ./mlruns:/app/mlruns
    networks:
      - customer_retention_network

  streamlit_ui:
    build:
        context: src/streamlit_ui
        dockerfile: Dockerfile
    restart: always
    ports:
      - "8501:8501"
    networks:
      - customer_retention_network
    depends_on:
      - ml_stack

  prefect-server:
    image: prefecthq/prefect:2-latest
    container_name: prefect-server
    command: ["prefect", "server", "start"]
    ports:
      - "4200:4200"
    environment:
      - PREFECT_UI_URL=http://localhost:4200
      - PREFECT_API_URL=http://localhost:4200/api
    networks:
      - customer_retention_network
    depends_on:
      - ml_stack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5


  monitor:
    build:
      context: src/monitoring
      dockerfile: Dockerfile
    environment:
      - config_path=${config_path}
      - PREFECT_API_URL=http://prefect-server:4200/api
    ports:
      - "8003:8003"
    expose:
      - 8003
    volumes:
      - ./databases:/app/databases
      - ./configs:/app/configs
    depends_on:
      - prefect-server
    networks:
      - customer_retention_network
