database:
  db_path: ./databases/customer.db

data:
  raw_data:
    name: "rawdata"
    path: "./data/raw_data/Churn.csv"
  processed_data:
    name: "processdata"
    path: './data/churn-data/processed_data/churn.csv'
    dropcols: []
    targetcolumn: "churn"
