base:
  random_state: 11
  artifact_path: "model"
  developer: "Godwin"
  model: ["linearmodel", "decisiontree","randomforest", "xgboost"]

database:
  tracking:
    tracking_url: 'sqlite:///databases/mlflow.db'
    experiment_name: 'CustomerChurn'
  customer:
    database_path: ./databases/customer.db
    prediction_logs: "prediction_logs"
    model_metrics: metrics_logs
    systemmetrics: system_metrics_logs

data:
  raw:
    path: "./data/raw_data/Churn.csv"
    name: "rawdata"
  process:
    path: './data/churn-data/processed_data/churn.csv'
    name: "processdata"
    dropcols: []
    targetcolumn:
  test_size: 0.3

hyperparameters:
  tree_models:
    min_depth: 1
    max_depth: 15
    min_sample_split: 2
    max_sample_split: 15
    min_sample_leaf: 1
    max_sample_leaf: 15
    criterion: ["gini", "entropy"]
  linear_model:
    min_c: 1
    max_c: 15
    interval: 2
  xgboost:
    min_depth: 1
    max_depth: 15
    min_learning_rate: -3
    max_learning_rate: 0
    min_child_weight: 1
    max_child_weight: 3
    objective: 'binary:logistic'
    eval_metric: logloss
