global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "prefect"
    static_configs:
      - targets: ["prefect:4200"]

  - job_name: "monitor"
    static_configs:
      - targets: ["monitor:8003"]
