name: Deploy Prefect flow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Prefect
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set Environment Variables
        id: set-output
        run: |
          echo "PREFECT_API_KEY=${{ secrets.PREFECT_KEY }}" >> $GITHUB_ENV
          echo "PREFECT_WORKSPACE=${{ secrets.PREFECT_WORKSPACE }}" >> $GITHUB_ENV

      - name: Prefect Deploy
        run: |
          pip install -r requirements.txt
          prefect cloud login --key=$PREFECT_API_KEY --workspace=$PREFECT_WORKSPACE
          python deployment_flow.py
